language: cpp

# safelist
branches:
  only:
  - master
  - dev

compiler:
  - gcc

cache: ccache

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libevent-dev
      - gcc-7
      - g++-7
      - libboost-all-dev
    env:
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
- eval "${MATRIX_EVAL}"
- chmod 755 build_env.sh
- sudo ./build_env.sh
- sudo ./autogen.sh
install:
  

script: mkdir -p build && cd build && cmake -DENABLE_TEST=ON .. && make && ./bin/example

